### ISSUE TITLE
Edit paper for style and clarity

### ISSUE THREAD

**Issue by rmsare** [CosmiQ/CometTS#16]
The paper has been improved, but I feel like some detail is missing. The main issues I see are: 

- [ ] The core contribution could be better defined in the second paragraph.

Right now, the paper states that CometTS provides new functionality in moving window statistics, extracting a time series from an ROI, and cloud masking. SITS, for one, has ARIMA functionality, and TIMESAT and SITS provide cloud/QA filtering, so I don't think these are the new, key features of CometTS. You should probably emphasize other unique advantages of CometTS as a rapid inspection workflow while mentioning these as important features.

- [x] There is some redundant use of the first person. For instance,  you could edit the first sentence to remove "We have developed .. that we called" to more directly describe the software. This would be something like: "Comet Time Series (CometTS) is a set of Python notebooks that enables analysis and visualization of a time series of satellite imagery for the data science and geographic communities."

- [x] I think "geography community" is a better term for the set of researchers in this field.

- [x] Typo in the last paragraph of the paper ("calucluated" -> "calculated"). 

([JOSS review thread](https://github.com/openjournals/joss-reviews/issues/1047))

**Comment by rmsare** [comment]
Thanks you for the edits. It's nearly there, but these issues remain in the text:

- [x] First paragraph: 'geographic' should be 'geography community' or 'geographic science community'
- [ ] Second paragraph: "adds new functionality to the ... domain" should be "includes functionality for overhead time series analysis and visualization", because this functionality is present in existing TSA packages.
- [x] Typo in the last paragraph of the paper ("calucluated" -> "calculated")

**Comment by Kevin-Mattheus-Moerman** [comment]
@jshermeyer can you finalize these steps and report back over at https://github.com/openjournals/joss-reviews/issues/1047?

**Comment by jshermeyer** [comment]
Apologies for the delay, I've been traveling/preoccupied.  I feel like today is the first time I've actually seen this issue for some reason so that could contribute to my tepid edits.  I've fixed two of the three issues noted by @rmsare. I'm pushing back on the second paragraph change, it presently reads:

> Specifically, ``CometTS`` output includes user-specified statistics such as mean, median, and quartiles, across arbitrarily sized regions of interest (ROI). Furthermore, the option for anomaly detection is also included, and ``CometTS`` leverages an Auto-Regressive Integrated Moving Average (ARIMA) analysis to quantify trends and test if observations are significantly different from observed historical trends. 

One of the main motivations for creating Comet was to handle arbitrarily sized regions and polygon geometries.  Previous methods work only on single pixels and then drill down through the entire image stack to extract relevant statistics and visualize for just that one pixel.  This isn't great when you're interested in broader areas and aggregating stats over both space and time, and Comet helps to fill this gap.  Furthermore, although ARIMA is incorporated in other packages (i.e. SITS) to remove anomalies like clouds, Comet uses it in a new way, splitting data into a "before" and "after" event to automatically flag anomalies.  I think this is a novel application in a software context, but I don't claim it's the most novel thing about Comet in the text either.

**Comment by rmsare** [comment]
Thanks for clarifying - very helpful.

Looks good to me, @jshermeyer @Kevin-Mattheus-Moerman .
